#!/usr/bin/env bash
# git-operations.sh - Git commit and PR creation for workers
#
# Provides functions for creating commits and pull requests from worker workspaces.
# Used by both lib/worker.sh and bin/wiggum-worker for consistent git operations.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/logger.sh"
source "$SCRIPT_DIR/calculate-cost.sh"

# Create a commit in the worker workspace
# Args: <workspace> <task_id> <task_desc> <task_priority> <worker_id>
# Sets: GIT_COMMIT_BRANCH (branch name on success, empty on failure)
# Returns: 0 on success, 1 on failure
git_create_commit() {
    local workspace="$1"
    local task_id="$2"
    local task_desc="$3"
    local task_priority="${4:-MEDIUM}"
    local worker_id="$5"

    cd "$workspace" || {
        log_error "Failed to cd to workspace: $workspace"
        GIT_COMMIT_BRANCH=""
        return 1
    }

    # Check if there are changes to commit
    if git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
        log_error "No changes to commit for $task_id"
        GIT_COMMIT_BRANCH=""
        return 1
    fi

    log "Creating branch and commit for $task_id"

    # Create a unique branch for this task attempt
    local timestamp=$(date +%s)
    local branch_name="task/$task_id-$timestamp"

    if ! git checkout -b "$branch_name" 2>&1; then
        log_error "Failed to create branch $branch_name"
        GIT_COMMIT_BRANCH=""
        return 1
    fi

    # Stage all changes
    git add -A

    # Create commit message
    local commit_msg="${task_id}: ${task_desc}

Worker: $worker_id
Priority: ${task_priority}
Completed by Chief Wiggum autonomous worker.

Co-Authored-By: Chief Wiggum Worker <noreply@chief-wiggum.local>"

    if ! git commit --no-gpg-sign -m "$commit_msg" 2>&1; then
        log_error "Failed to create commit"
        GIT_COMMIT_BRANCH=""
        return 1
    fi

    local commit_hash=$(git rev-parse HEAD)
    log "Created commit: $commit_hash on branch $branch_name"

    GIT_COMMIT_BRANCH="$branch_name"
    return 0
}

# Create a pull request for a worker's branch
# Args: <branch_name> <task_id> <task_desc> <worker_dir> [project_dir]
# Sets: GIT_PR_URL (PR URL on success, "N/A" on failure)
# Returns: 0 on success, 1 on failure
git_create_pr() {
    local branch_name="$1"
    local task_id="$2"
    local task_desc="$3"
    local worker_dir="$4"
    local project_dir="${5:-$PROJECT_DIR}"

    GIT_PR_URL="N/A"

    # Push the branch
    if ! git push -u origin "$branch_name" 2>&1; then
        log_error "Failed to push branch $branch_name"
        return 1
    fi

    log "Pushed branch $branch_name to remote"

    # Check if gh CLI is available
    if ! command -v gh &> /dev/null; then
        log "gh CLI not found, skipping PR creation. Branch pushed: $branch_name"
        return 1
    fi

    # Build PR body
    local changes_section="This PR contains the automated implementation of the task requirements."
    if [ -f "$worker_dir/summary.txt" ]; then
        changes_section=$(cat "$worker_dir/summary.txt")
    fi

    # Calculate and include metrics if available
    local metrics_section=""
    if [ -f "$worker_dir/worker.log" ]; then
        calculate_worker_cost "$worker_dir/worker.log" > "$worker_dir/metrics.txt" 2>&1 || true
        if [ -f "$worker_dir/metrics.txt" ]; then
            metrics_section="
## Metrics

\`\`\`
$(tail -n +3 "$worker_dir/metrics.txt")
\`\`\`
"
        fi
    fi

    # Read PRD for summary
    local prd_body=""
    if [ -f "$worker_dir/prd.md" ]; then
        prd_body=$(cat "$worker_dir/prd.md")
    fi

    local pr_body="## Summary

$prd_body

## Changes

${changes_section}
${metrics_section}
---
🤖 Generated by [Chief Wiggum](https://github.com/0kenx/chief-wiggum)"

    # Create the PR
    if gh pr create \
        --title "$task_id: $task_desc" \
        --body "$pr_body" \
        --base main \
        --head "$branch_name" 2>&1; then

        log "Created Pull Request for $task_id"

        # Get and save PR URL
        GIT_PR_URL=$(gh pr view "$branch_name" --json url -q .url 2>/dev/null || echo "N/A")
        echo "$GIT_PR_URL" > "$worker_dir/pr_url.txt"
        return 0
    else
        log_error "Failed to create PR (gh CLI error), but branch is pushed"
        return 1
    fi
}

# Verify that a commit has been pushed and PR exists on GitHub
# Args: <workspace> <task_id>
# Returns: 0 if verified, 1 if not
git_verify_pushed() {
    local workspace="$1"
    local task_id="$2"

    # Get local commit from worktree
    local local_commit
    local_commit=$(git -C "$workspace" rev-parse HEAD 2>/dev/null)

    # Check if commit exists on remote branch and PR exists
    local remote_commit
    remote_commit=$(git ls-remote --heads origin "task/$task_id-*" 2>/dev/null | head -1 | cut -f1)

    local pr_exists
    pr_exists=$(gh pr list --head "task/$task_id-*" --json number -q '.[0].number' 2>/dev/null)

    if [ -n "$remote_commit" ] && [ "$local_commit" = "$remote_commit" ] && [ -n "$pr_exists" ]; then
        log_debug "Verified: commit $local_commit pushed and PR #$pr_exists exists on GitHub"
        return 0
    else
        log "GitHub verification failed: local=$local_commit, remote=${remote_commit:-none}, pr=$([ -n "$pr_exists" ] && echo '#'$pr_exists || echo 'no')"
        return 1
    fi
}

# Full commit and PR workflow for a completed worker
# Args: <worker_dir> <task_id> <project_dir>
# Sets: GIT_COMMIT_BRANCH, GIT_PR_URL
# Returns: 0 on success, 1 on failure
git_finalize_worker() {
    local worker_dir="$1"
    local task_id="$2"
    local project_dir="$3"
    local workspace="$worker_dir/workspace"
    local worker_id
    worker_id=$(basename "$worker_dir")

    if [ ! -d "$workspace" ]; then
        log_error "Workspace not found: $workspace"
        return 1
    fi

    cd "$workspace" || return 1

    # Get task description from kanban
    local task_desc
    task_desc=$(grep "**\[$task_id\]**" "$project_dir/.ralph/kanban.md" 2>/dev/null | sed 's/.*\*\*\[.*\]\*\* //' | head -1)

    # Get task priority
    local task_priority
    task_priority=$(grep -A2 "**\[$task_id\]**" "$project_dir/.ralph/kanban.md" 2>/dev/null | grep "Priority:" | sed 's/.*Priority: //')

    # Create commit
    if ! git_create_commit "$workspace" "$task_id" "$task_desc" "$task_priority" "$worker_id"; then
        return 1
    fi

    # Create PR
    if ! git_create_pr "$GIT_COMMIT_BRANCH" "$task_id" "$task_desc" "$worker_dir" "$project_dir"; then
        # Branch was pushed but PR creation failed - partial success
        return 1
    fi

    return 0
}
