#!/usr/bin/env bash
# Worker script - spawned by chief for each task

WORKER_DIR="$1"         # e.g., .ralph/workers/worker-TASK-001-12345
PROJECT_DIR="$2"        # Project root directory
CHIEF_HOME="${CHIEF_HOME:-$HOME/.claude/chief-wiggum}"

source "$CHIEF_HOME/lib/ralph-loop.sh"
source "$CHIEF_HOME/lib/logger.sh"

main() {
    log "Worker starting: $WORKER_ID for task $TASK_ID"

    setup_worker

    # Start Ralph loop for this worker's task
    if ralph_loop \
        "$WORKER_DIR/prd.md" \
        "$CHIEF_HOME/config/worker-agent.md" \
        "$WORKER_DIR/workspace" \
        50; then
        log "Worker $WORKER_ID completed successfully"
    else
        log_error "Worker $WORKER_ID failed or timed out"
    fi

    cleanup_worker
    log "Worker finished: $WORKER_ID"
}

setup_worker() {
    # Create git worktree for isolation
    cd "$PROJECT_DIR" || exit 1

    log_debug "Creating git worktree at $WORKER_DIR/workspace"
    git worktree add "$WORKER_DIR/workspace" HEAD 2>&1 | tee -a "$WORKER_DIR/worker.log"

    # Setup hooks
    export CLAUDE_HOOKS_CONFIG="$CHIEF_HOME/hooks/worker-hooks.json"
    export WORKER_ID
    export TASK_ID
}

cleanup_worker() {
    log "Cleaning up worker $WORKER_ID"

    if [ -d "$WORKER_DIR/workspace" ]; then
        cd "$WORKER_DIR/workspace" || return 1

        # Get task description from kanban for commit message
        local task_desc=$(grep "**\[$TASK_ID\]**" "$PROJECT_DIR/.ralph/kanban.md" | sed 's/.*\*\*\[.*\]\*\* //' | head -1)

        # Get task priority
        local task_priority=$(grep -A2 "**\[$TASK_ID\]**" "$PROJECT_DIR/.ralph/kanban.md" | grep "Priority:" | sed 's/.*Priority: //')

        # Commit any changes in the worktree
        if ! git diff --quiet || ! git diff --cached --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
            log "Creating branch and PR for $TASK_ID"

            # Create a branch for this task
            local branch_name="task/$TASK_ID"
            git checkout -b "$branch_name" 2>&1 | tee -a "$WORKER_DIR/worker.log"

            # Stage all changes
            git add -A

            # Create commit
            local commit_msg="${TASK_ID}: ${task_desc}

Worker: $WORKER_ID
Priority: ${task_priority:-MEDIUM}
Completed by Chief Wiggum autonomous worker.

Co-Authored-By: Chief Wiggum Worker <noreply@chief-wiggum.local>"

            git commit -m "$commit_msg" 2>&1 | tee -a "$WORKER_DIR/worker.log"

            local commit_hash=$(git rev-parse HEAD)
            log "Created commit: $commit_hash on branch $branch_name"

            # Push the branch
            if git push -u origin "$branch_name" 2>&1 | tee -a "$WORKER_DIR/worker.log"; then
                log "Pushed branch $branch_name to remote"

                # Create Pull Request using gh CLI
                if command -v gh &> /dev/null; then
                    local pr_body="## Summary
Automated PR for $TASK_ID created by Chief Wiggum worker.

**Task Description:** $task_desc
**Priority:** ${task_priority:-MEDIUM}
**Worker ID:** $WORKER_ID

## Changes
This PR contains the automated implementation of the task requirements.

---
🤖 Generated by [Chief Wiggum](https://github.com/anthropics/chief-wiggum)"

                    if gh pr create \
                        --title "$TASK_ID: $task_desc" \
                        --body "$pr_body" \
                        --base main \
                        --head "$branch_name" 2>&1 | tee -a "$WORKER_DIR/worker.log"; then

                        log "✓ Created Pull Request for $TASK_ID"

                        # Save PR URL
                        gh pr view "$branch_name" --json url -q .url > "$WORKER_DIR/pr_url.txt"
                    else
                        log "Failed to create PR (gh CLI error), but branch is pushed"
                    fi
                else
                    log "gh CLI not found, skipping PR creation. Branch pushed: $branch_name"
                fi
            else
                log "Failed to push branch (no remote configured?)"
            fi
        else
            log "No changes to commit for $TASK_ID"
        fi
    fi

    # Clean up git worktree
    cd "$PROJECT_DIR" || exit 1
    log_debug "Removing git worktree"
    git worktree remove "$WORKER_DIR/workspace" --force 2>&1 | tee -a "$WORKER_DIR/worker.log" || true

    # Mark task complete in kanban (simple sed)
    log "Marking task $TASK_ID as complete in kanban"
    sed -i "s/- \[ \] \*\*\[$TASK_ID\]\*\*/- [x] **[$TASK_ID]**/" "$PROJECT_DIR/.ralph/kanban.md"

    log "Worker $WORKER_ID completed task $TASK_ID"
}

main "$@"
